In [6]:
import pandas as pd

sales = pd.read_csv('ecommerce_sales.csv')

In [7]:
sales.shape

(20, 7)

In [8]:
sales.head()

   Order_ID Customer_Name     Product     Category  Quantity  Price       City
0      1001           Ali      Laptop  Electronics         1  80000     Lahore
1      1002          Sara       Phone  Electronics         2  50000    Karachi
2      1003         Ahmed       Chair    Furniture         4   7000  Islamabad
3      1004          Amna       Table    Furniture         1  12000     Lahore
4      1005          Nida  Headphones  Electronics         3   5000    Karachi

In [9]:
# new total sales column
sales['Total Sales'] = sales['Quantity'] * sales['Price']

sales

,Order_ID,Customer_Name,Product,Category,Quantity,Price,City,Total Sales
0,1001,Ali,Laptop,Electronics,1,80000,Lahore,80000
1,1002,Sara,Phone,Electronics,2,50000,Karachi,100000
2,1003,Ahmed,Chair,Furniture,4,7000,Islamabad,28000
3,1004,Amna,Table,Furniture,1,12000,Lahore,12000
4,1005,Nida,Headphones,Electronics,3,5000,Karachi,15000
5,1006,Hassan,Keyboard,Electronics,2,3000,Rawalpindi,6000
6,1007,Ayesha,Sofa,Furniture,1,45000,Lahore,45000
7,1008,Usman,Monitor,Electronics,2,25000,Islamabad,50000
8,1009,Maria,Lamp,Home,5,2000,Karachi,10000
9,1010,Bilal,Desk,Furniture,2,15000,Lahore,30000
10,1011,Zara,Mouse,Electronics,4,1500,Rawalpindi,6000
11,1012,Ali,Phone,Electronics,1,52000,Lahore,52000
12,1013,Sana,Bed,Furniture,1,60000,Islamabad,60000
13,1014,Hamza,Camera,Electronics,1,70000,Karachi,70000
14,1015,Hina,Curtain,Home,6,1000,Lahore,6000
15,1016,Ahmed,Notebook,Stationery,10,200,Rawalpindi,2000
16,1017,Fatima,Pen,Stationery,20,50,Islamabad,1000
17,1018,Omar,Printer,Electronics,1,30000,Karachi,30000
18,1019,Noor,Shelf,Furniture,3,8000,Lahore,24000
19,1020,Saad,Bag,Stationery,5,2500,Rawalpindi,12500

In [12]:
sales.groupby('Product')['Total Sales'].sum()

Product
Bag            12500
Bed            60000
Camera         70000
Chair          28000
Curtain         6000
Desk           30000
Headphones     15000
Keyboard        6000
Lamp           10000
Laptop         80000
Monitor        50000
Mouse           6000
Notebook        2000
Pen             1000
Phone         152000
Printer        30000
Shelf          24000
Sofa           45000
Table          12000
Name: Total Sales, dtype: int64

In [13]:
sales.groupby('Product')['Total Sales'].sum().idxmax()

'Phone'

Phone generated the highest total sales among all products in the dataset

In [14]:
sales.groupby('Product')['Total Sales'].sum().idxmin()

'Pen'

Pen generated the lowest total sales among all products in the dataset

In [16]:
sales.groupby('City')['Total Sales'].sum()

City
Islamabad     139000
Karachi       225000
Lahore        249000
Rawalpindi     26500
Name: Total Sales, dtype: int64

Lahore generated the highest total sales (265,000), followed by Karachi (225,000) and Islamabad (139,000). This indicates that Lahore is the strongest performing city in terms of sales revenue within this dataset.

In [17]:
sales.groupby('City')['Total Sales'].sum().idxmax()

'Lahore'

In [18]:
sales.groupby('City')['Total Sales'].sum().idxmin()

'Rawalpindi'

In [23]:
 electronics = sales['Category']== 'Electronics'

In [25]:
sales.loc[electronics,['Product']]

       Product
0       Laptop
1        Phone
4   Headphones
5     Keyboard
7      Monitor
10       Mouse
11       Phone
13      Camera
17     Printer

In [26]:
sales['Total Sales'].mean()

np.float64(31975.0)

In [28]:
#top 5 expensive order

sales.sort_values('Price')

,Order_ID,Customer_Name,Product,Category,Quantity,Price,City,Total Sales
16,1017,Fatima,Pen,Stationery,20,50,Islamabad,1000
15,1016,Ahmed,Notebook,Stationery,10,200,Rawalpindi,2000
14,1015,Hina,Curtain,Home,6,1000,Lahore,6000
10,1011,Zara,Mouse,Electronics,4,1500,Rawalpindi,6000
8,1009,Maria,Lamp,Home,5,2000,Karachi,10000
19,1020,Saad,Bag,Stationery,5,2500,Rawalpindi,12500
5,1006,Hassan,Keyboard,Electronics,2,3000,Rawalpindi,6000
4,1005,Nida,Headphones,Electronics,3,5000,Karachi,15000
2,1003,Ahmed,Chair,Furniture,4,7000,Islamabad,28000
18,1019,Noor,Shelf,Furniture,3,8000,Lahore,24000
3,1004,Amna,Table,Furniture,1,12000,Lahore,12000
9,1010,Bilal,Desk,Furniture,2,15000,Lahore,30000
7,1008,Usman,Monitor,Electronics,2,25000,Islamabad,50000
17,1018,Omar,Printer,Electronics,1,30000,Karachi,30000
6,1007,Ayesha,Sofa,Furniture,1,45000,Lahore,45000
1,1002,Sara,Phone,Electronics,2,50000,Karachi,100000
11,1012,Ali,Phone,Electronics,1,52000,Lahore,52000
12,1013,Sana,Bed,Furniture,1,60000,Islamabad,60000
13,1014,Hamza,Camera,Electronics,1,70000,Karachi,70000
0,1001,Ali,Laptop,Electronics,1,80000,Lahore,80000

In [30]:
sales.sort_values('Price' , ascending = False)

,Order_ID,Customer_Name,Product,Category,Quantity,Price,City,Total Sales
0,1001,Ali,Laptop,Electronics,1,80000,Lahore,80000
13,1014,Hamza,Camera,Electronics,1,70000,Karachi,70000
12,1013,Sana,Bed,Furniture,1,60000,Islamabad,60000
11,1012,Ali,Phone,Electronics,1,52000,Lahore,52000
1,1002,Sara,Phone,Electronics,2,50000,Karachi,100000
6,1007,Ayesha,Sofa,Furniture,1,45000,Lahore,45000
17,1018,Omar,Printer,Electronics,1,30000,Karachi,30000
7,1008,Usman,Monitor,Electronics,2,25000,Islamabad,50000
9,1010,Bilal,Desk,Furniture,2,15000,Lahore,30000
3,1004,Amna,Table,Furniture,1,12000,Lahore,12000
18,1019,Noor,Shelf,Furniture,3,8000,Lahore,24000
2,1003,Ahmed,Chair,Furniture,4,7000,Islamabad,28000
4,1005,Nida,Headphones,Electronics,3,5000,Karachi,15000
5,1006,Hassan,Keyboard,Electronics,2,3000,Rawalpindi,6000
19,1020,Saad,Bag,Stationery,5,2500,Rawalpindi,12500
8,1009,Maria,Lamp,Home,5,2000,Karachi,10000
10,1011,Zara,Mouse,Electronics,4,1500,Rawalpindi,6000
14,1015,Hina,Curtain,Home,6,1000,Lahore,6000
15,1016,Ahmed,Notebook,Stationery,10,200,Rawalpindi,2000
16,1017,Fatima,Pen,Stationery,20,50,Islamabad,1000

In [32]:
sales.sort_values('Price',ascending= False).head(5)

,Order_ID,Customer_Name,Product,Category,Quantity,Price,City,Total Sales
0,1001,Ali,Laptop,Electronics,1,80000,Lahore,80000
13,1014,Hamza,Camera,Electronics,1,70000,Karachi,70000
12,1013,Sana,Bed,Furniture,1,60000,Islamabad,60000
11,1012,Ali,Phone,Electronics,1,52000,Lahore,52000
1,1002,Sara,Phone,Electronics,2,50000,Karachi,100000

The most expesive product in the datset is latop,followed by the camera. Most of the high priced products belong to the Electronic categories with only the one product from the furniture category appearing among the top 5 most expesive items.

The sale quantity of mostly these items are 1 unit which indicates that their higher revenue contibution is mainly due to their higher prices rather then higher sales volume.

In [33]:
#Total no of each product sold

sales.groupby('Product')['Quantity'].sum()

Product
Bag            5
Bed            1
Camera         1
Chair          4
Curtain        6
Desk           2
Headphones     3
Keyboard       2
Lamp           5
Laptop         1
Monitor        2
Mouse          4
Notebook      10
Pen           20
Phone          3
Printer        1
Shelf          3
Sofa           1
Table          1
Name: Quantity, dtype: int64

PEN has the highest quantity soled(20 units) followed by the NOTEBOOK this indicates that stationery products have higher sales volume as compared to the other categories.