In [2]:
import pandas as pd

students_record = pd.read_csv("students_data.csv")

In [5]:
#to_check_no_of_rows_and_columns_in_data
#we_dont_use_()_bcz_shape_is_attribute_not_function

students_record.shape

(20, 7)

In [6]:
#for_first_five_rows
students_record.head()

  Student_ID    Name  Math  English  Science  Attendance        City
0       S001    Amna    90       85       95          92  Rawalpindi
1       S002     Ali    70       75       80          85      Lahore
2       S003    Sara    88       92       90          95     Karachi
3       S004   Ahmed    60       65       70          78   Islamabad
4       S005  Ayesha    95       90       98          96  Rawalpindi

In [7]:
#for_info

students_record.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  20 non-null     object
 1   Name        20 non-null     object
 2   Math        20 non-null     int64
 3   English     20 non-null     int64
 4   Science     20 non-null     int64
 5   Attendance  20 non-null     int64
 6   City        20 non-null     object
dtypes: int64(4), object(3)
memory usage: 1.2+ KB

In [26]:
#changing index to name

student_record = students_record.set_index('Name')
student_record

        Student_ID  Math  English  Science  Attendance        City
Name
Amna          S001    90       85       95          92  Rawalpindi
Ali           S002    70       75       80          85      Lahore
Sara          S003    88       92       90          95     Karachi
Ahmed         S004    60       65       70          78   Islamabad
Ayesha        S005    95       90       98          96  Rawalpindi
Hamza         S006    55       60       58          70      Lahore
Zara          S007    82       85       88          90     Karachi
Bilal         S008    75       70       78          82   Islamabad
Hira          S009    92       94       91          98  Rawalpindi
Usman         S010    68       72       65          75      Lahore
Noor          S011    85       88       90          93     Karachi
Hassan        S012    45       55       50          65   Islamabad
Fatima        S013    78       80       82          88  Rawalpindi
Zain          S014    65       68       70          80      Lahore
Maryam        S015    91       89       94          97     Karachi
Saad          S016    72       74       76          84   Islamabad
Iqra          S017    87       90       85          91  Rawalpindi
Daniyal       S018    58       62       60          72      Lahore
Laiba         S019    80       83       86          89     Karachi
Hassan        S020    50       48       55          68   Islamabad

In [34]:
#only_names

students_record.loc[:,'Name']

0        Amna
1         Ali
2        Sara
3       Ahmed
4      Ayesha
5       Hamza
6        Zara
7       Bilal
8        Hira
9       Usman
10       Noor
11     Hassan
12     Fatima
13       Zain
14     Maryam
15       Saad
16       Iqra
17    Daniyal
18      Laiba
19     Hassan
Name: Name, dtype: object

In [30]:
#only_maths and science coloumn
students_record.loc[:,['Math','Science']]

    Math  Science
0     90       95
1     70       80
2     88       90
3     60       70
4     95       98
5     55       58
6     82       88
7     75       78
8     92       91
9     68       65
10    85       90
11    45       50
12    78       82
13    65       70
14    91       94
15    72       76
16    87       85
17    58       60
18    80       86
19    50       55

In [35]:
#only first five students name and math score

students_record.loc[:4,['Name','Math']]

     Name  Math
0    Amna    90
1     Ali    70
2    Sara    88
3   Ahmed    60
4  Ayesha    95

In [6]:
# new coloumn
students_record['Total Marks'] = students_record['Math'] + students_record['English'] + students_record['Science']
students_record

,Student_ID,Name,Math,English,Science,Attendance,City,total marks,Total Marks
0,S001,Amna,90,85,95,92,Rawalpindi,270,270
1,S002,Ali,70,75,80,85,Lahore,225,225
2,S003,Sara,88,92,90,95,Karachi,270,270
3,S004,Ahmed,60,65,70,78,Islamabad,195,195
4,S005,Ayesha,95,90,98,96,Rawalpindi,283,283
5,S006,Hamza,55,60,58,70,Lahore,173,173
6,S007,Zara,82,85,88,90,Karachi,255,255
7,S008,Bilal,75,70,78,82,Islamabad,223,223
8,S009,Hira,92,94,91,98,Rawalpindi,277,277
9,S010,Usman,68,72,65,75,Lahore,205,205
10,S011,Noor,85,88,90,93,Karachi,263,263
11,S012,Hassan,45,55,50,65,Islamabad,150,150
12,S013,Fatima,78,80,82,88,Rawalpindi,240,240
13,S014,Zain,65,68,70,80,Lahore,203,203
14,S015,Maryam,91,89,94,97,Karachi,274,274
15,S016,Saad,72,74,76,84,Islamabad,222,222
16,S017,Iqra,87,90,85,91,Rawalpindi,262,262
17,S018,Daniyal,58,62,60,72,Lahore,180,180
18,S019,Laiba,80,83,86,89,Karachi,249,249
19,S020,Hassan,50,48,55,68,Islamabad,153,153

In [8]:
students_record['Percentage'] = students_record['Total Marks']/3
students_record

,Student_ID,Name,Math,English,Science,Attendance,City,total marks,Total Marks,Percentage
0,S001,Amna,90,85,95,92,Rawalpindi,270,270,90.000000
1,S002,Ali,70,75,80,85,Lahore,225,225,75.000000
2,S003,Sara,88,92,90,95,Karachi,270,270,90.000000
3,S004,Ahmed,60,65,70,78,Islamabad,195,195,65.000000
4,S005,Ayesha,95,90,98,96,Rawalpindi,283,283,94.333333
5,S006,Hamza,55,60,58,70,Lahore,173,173,57.666667
6,S007,Zara,82,85,88,90,Karachi,255,255,85.000000
7,S008,Bilal,75,70,78,82,Islamabad,223,223,74.333333
8,S009,Hira,92,94,91,98,Rawalpindi,277,277,92.333333
9,S010,Usman,68,72,65,75,Lahore,205,205,68.333333
10,S011,Noor,85,88,90,93,Karachi,263,263,87.666667
11,S012,Hassan,45,55,50,65,Islamabad,150,150,50.000000
12,S013,Fatima,78,80,82,88,Rawalpindi,240,240,80.000000
13,S014,Zain,65,68,70,80,Lahore,203,203,67.666667
14,S015,Maryam,91,89,94,97,Karachi,274,274,91.333333
15,S016,Saad,72,74,76,84,Islamabad,222,222,74.000000
16,S017,Iqra,87,90,85,91,Rawalpindi,262,262,87.333333
17,S018,Daniyal,58,62,60,72,Lahore,180,180,60.000000
18,S019,Laiba,80,83,86,89,Karachi,249,249,83.000000
19,S020,Hassan,50,48,55,68,Islamabad,153,153,51.000000

In [16]:
#removing total marks column

students_record = students_record.drop('total marks',axis =1)

In [17]:
def grade(percentage):
    if percentage >= 80:
        return 'A'
    elif percentage >= 70:
        return 'B'
    elif percentage >= 50:
        return 'C'
    else:
        return 'Fail'

students_record['Grade'] = students_record['Percentage'].apply(grade)
students_record

,Student_ID,Name,Math,English,Science,Attendance,City,Total Marks,Percentage,Grade
0,S001,Amna,90,85,95,92,Rawalpindi,270,90.000000,A
1,S002,Ali,70,75,80,85,Lahore,225,75.000000,B
2,S003,Sara,88,92,90,95,Karachi,270,90.000000,A
3,S004,Ahmed,60,65,70,78,Islamabad,195,65.000000,C
4,S005,Ayesha,95,90,98,96,Rawalpindi,283,94.333333,A
5,S006,Hamza,55,60,58,70,Lahore,173,57.666667,C
6,S007,Zara,82,85,88,90,Karachi,255,85.000000,A
7,S008,Bilal,75,70,78,82,Islamabad,223,74.333333,B
8,S009,Hira,92,94,91,98,Rawalpindi,277,92.333333,A
9,S010,Usman,68,72,65,75,Lahore,205,68.333333,C
10,S011,Noor,85,88,90,93,Karachi,263,87.666667,A
11,S012,Hassan,45,55,50,65,Islamabad,150,50.000000,C
12,S013,Fatima,78,80,82,88,Rawalpindi,240,80.000000,A
13,S014,Zain,65,68,70,80,Lahore,203,67.666667,C
14,S015,Maryam,91,89,94,97,Karachi,274,91.333333,A
15,S016,Saad,72,74,76,84,Islamabad,222,74.000000,B
16,S017,Iqra,87,90,85,91,Rawalpindi,262,87.333333,A
17,S018,Daniyal,58,62,60,72,Lahore,180,60.000000,C
18,S019,Laiba,80,83,86,89,Karachi,249,83.000000,A
19,S020,Hassan,50,48,55,68,Islamabad,153,51.000000,C

In [18]:
#average percentage of class

students_record.Percentage.mean()

np.float64(76.19999999999999)

In [19]:
#finding topper
topper = students_record['Percentage'].idxmax()

In [21]:
students_record.loc[topper,['Name','Percentage','City']]

Name              Ayesha
Percentage     94.333333
City          Rawalpindi
Name: 4, dtype: object

In [22]:
#finding lowest marks
min_marks = students_record['Percentage'].idxmin()
students_record.loc[min_marks,['Name','Percentage','City']]

Name             Hassan
Percentage         50.0
City          Islamabad
Name: 11, dtype: object

In [23]:
students_record['Grade'].value_counts()

Grade
A    10
C     7
B     3
Name: count, dtype: int64

In [24]:
#filtering

students_record['Percentage'] > 80

0      True
1     False
2      True
3     False
4      True
5     False
6      True
7     False
8      True
9     False
10     True
11    False
12    False
13    False
14     True
15    False
16     True
17    False
18     True
19    False
Name: Percentage, dtype: bool

In [26]:
students_record.loc[students_record['Percentage'] > 80,['Name','Percentage','Total Marks']]

      Name  Percentage  Total Marks
0     Amna   90.000000          270
2     Sara   90.000000          270
4   Ayesha   94.333333          283
6     Zara   85.000000          255
8     Hira   92.333333          277
10    Noor   87.666667          263
14  Maryam   91.333333          274
16    Iqra   87.333333          262
18   Laiba   83.000000          249

In [27]:
students_record['Attendance'] > 90

students_record.loc[students_record['Attendance'] >90,['Student_ID','Name','Attendance']]

   Student_ID    Name  Attendance
0        S001    Amna          92
2        S003    Sara          95
4        S005  Ayesha          96
8        S009    Hira          98
10       S011    Noor          93
14       S015  Maryam          97
16       S017    Iqra          91

In [34]:
students = (students_record['Percentage'] > 80) & (students_record['Attendance'] > 90)

students_record.loc[students,['Student_ID','Name','Attendance','Percentage']]

   Student_ID    Name  Attendance  Percentage
0        S001    Amna          92   90.000000
2        S003    Sara          95   90.000000
4        S005  Ayesha          96   94.333333
8        S009    Hira          98   92.333333
10       S011    Noor          93   87.666667
14       S015  Maryam          97   91.333333
16       S017    Iqra          91   87.333333

In [33]:
students_record.dtypes

Student_ID      object
Name            object
Math             int64
English          int64
Science          int64
Attendance       int64
City            object
Total Marks      int64
Percentage     float64
Grade           object
dtype: object