In [ ]:
import pandas as pd
students_record = pd.DataFrame({'Name':["Amna","Ansa","Nayab","Mmomina","Ayesha"],'Math':[90,80,85,93,70],'English':[78,89,59,65,80],'Science':[95,80,60,53,40]},index = ['S1','S2','S3','S4','S5'])
students_record.shape

(5, 4)

In [ ]:
students_record.head()

       Name  Math  English  Science
S1     Amna    90       78       95
S2     Ansa    80       89       80
S3    Nayab    85       59       60
S4  Mmomina    93       65       53
S5   Ayesha    70       80       40

In [ ]:
students_record['Name']

S1       Amna
S2       Ansa
S3      Nayab
S4    Mmomina
S5     Ayesha
Name: Name, dtype: object

In [ ]:
students_record[['Math','Science']]

    Math  Science
S1    90       95
S2    80       80
S3    85       60
S4    93       53
S5    70       40

In [ ]:
students_record['total'] = students_record['Math']+students_record['English']+students_record['Science']
students_record['percentage'] = students_record['total']/3
students_record

       Name  Math  English  Science  total  percentage
S1     Amna    90       78       95    263   87.666667
S2     Ansa    80       89       80    249   83.000000
S3    Nayab    85       59       60    204   68.000000
S4  Mmomina    93       65       53    211   70.333333
S5   Ayesha    70       80       40    190   63.333333

In [24]:
students_record.columns

Index(['Name', 'Math', 'English', 'Science', 'total', 'percentage'], dtype='object')

In [27]:
topper = print(['percentage'].max())

87.66666666666667

In [28]:
topper_student = students_record[students_record['percentage'] == students_record['percentage'].max()]
print(topper_student)

    Name  Math  English  Science  total  percentage
S1  Amna    90       78       95    263   87.666667

In [30]:
min_marks = students_record[students_record['percentage'] == students_record['percentage'].min()]
print(min_marks)

      Name  Math  English  Science  total  percentage
S5  Ayesha    70       80       40    190   63.333333